### ISSUE TITLE
Wechaty Developers Meetup: Shanghai, China, May 21, Thu, 2020

### ISSUE THREAD

**Issue by huan** [wechaty/PMC#6]
@lijiarui 话说，我周三周四在上海，咱们周四要不要上海的  contributor 聚一下呀

### 接龙

周四中午 上海 wechaty contributor 聚餐

1. ax4
2. 李佳芮
3. 人在江湖漂
4. （哥们儿）
5. 🔥 Alpha Sun🔥@MAKESURE.AI

**Comment by lijiarui** [comment]
![image](https://user-images.githubusercontent.com/6419514/82531666-5ef65380-9b72-11ea-88e9-9fb74b1eb625.png)

Cheers!

**Comment by ax4** [comment]
`Sorry, I leave a comment here, as a reminder. I will update this comment later. `
------

**Note：** 感谢5月21日周三中午的聚会，周四我们在Wechaty** Contributors群内，huan问我们是否能够更新一些回顾，告知大家我们周三聊了些什么。我在群里答应了一下，以comment的形式写一些回顾。但同时我这边周三之后直接“一键起飞🛫”：（作为一个观众和开源软件爱好者，看到） Bilibili直播区相关的一个开源软件`[弹幕库](https://www.danmaku.live/)`最近遇到了一个紧急事故需要抢修。自周一5月18日中午开始，由于B站直播区的弹幕协议v1->v2升级的原因，导致软件无法显示弹幕。而由于许多主播默认选择`[弹幕库]`作为他们的直播辅助工具，此次受灾情况逐渐打开变为严重。实际上简单的修复方案在4月份就已经提供了代码，在5月19日凌晨我也已经验证4月份的修复方案可以成功，但是由于开源软件知识的分布不均，相关的用户反馈和报错一直持续到周六5月23日都在发生。此时我也在撰写新的markdown教程来教学如何临时修复这个问题。而昨日深夜也形成了一个新的项目组来deliver新的软件。

**Comment by huan** [comment]
I have created another issue on wechaty.github.io and link to here.

If anyone interests in taking charge of writing this blog, please feel free to assign it to yourself, thank you very much! @ax4

**Comment by huan** [comment]
Hello @ax4 , do you have time to write our meetup blog recently?

If you have time, could we specify a DDL for it so that it will not be published too late?
If you have no time, let's ask other contributors to see if there's anyone who can write this great event for our community.

Looking forward to your reply, thank you very much!

**Comment by ax4** [comment]
Hi @huan, finally I have some time to do the blog writing. I will do it next week (Jul 25 - 31), so the DDL for me is on July 31st. 

But given that my point of view is limited, most of the summary part I could do is from my experience of Wechaty meeting 2017, 2018, 2020, and from the open code and issues. So I would prefer to journal some pieces of information from SH@May 21 Meeting, then focus my writing on many after-thought on Wechaty and Chatbot development. It will not be a full-detailed journal of SH@May 21 meeting, because it can hardly be 😉. 

Thanks for keeping interested!

**Comment by huan** [comment]
Awesome, great to know you will finish this blog post before August!

I'm looking forward to reading your great post, thank you very much!

**Comment by huan** [comment]
Hi @ax4, I hope you are doing well!

I'd like to follow up about the blog post of our contributor event in May, how about your blog post is going, have you finished writing it?

I'm looking forward to seeing your reply, thank you very much!

**Comment by huan** [comment]
I have no idea about whether this blog post has been published or not.

But let's close this issue for house cleaning.
